# Generated by Django 4.2.5 on 2023-10-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='text_files/'),
        ),
    ]
